[
{ "tag": "const", "name": "BAR", "location": "example.h:5:11", "type": { "tag": ":int" }, "value": 14 },
{ "tag": "const", "name": "Quux", "location": "example.h:6:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "abc" },
{ "tag": "extern", "name": "SomeExtern", "location": "example.h:8:12", "type": { "tag": ":int" } },
{ "tag": "function", "name": "blah", "location": "example.h:10:6", "parameters": [{ "tag": "parameter", "name": "x", "type": { "tag": ":pointer", "type": { "tag": ":pointer", "type": { "tag": ":char" } } } }], "return-type": { "tag": ":void" } },
{ "tag": "extern", "name": "foo", "location": "example.h:12:14", "type": { "tag": ":pointer", "type": { "tag": ":char" } } },
{ "tag": "struct", "name": "my_point", "location": "example.h:14:16", "fields": [{ "tag": "field", "name": "x", "type": { "tag": ":int" } }, { "tag": "field", "name": "y", "type": { "tag": ":int" } }, { "tag": "field", "name": "odd_value", "type": { "tag": ":array", "type": { "tag": ":int" }, "size": 15 } }] },
{ "tag": "typedef", "name": "my_point_t", "location": "example.h:18:3", "type": { "tag": ":struct", "name": "my_point" } },
{ "tag": "typedef", "name": "anonymous_t", "location": "example.h:22:3", "type": { "tag": "struct", "name": "", "location": "example.h:20:9", "fields": [{ "tag": "field", "name": "a", "type": { "tag": ":int" } }, { "tag": "field", "name": "b", "type": { "tag": ":int" } }] } },
{ "tag": "struct", "name": "some_struct", "location": "example.h:24:16", "fields": [{ "tag": "field", "name": "s", "type": { "tag": "struct", "name": "_some_internal_struct", "location": "example.h:25:10", "fields": [{ "tag": "field", "name": "a", "type": { "tag": "struct", "name": "", "location": "example.h:26:5", "fields": [{ "tag": "field", "name": "x", "type": { "tag": ":double" } }] } }, { "tag": "field", "name": "x", "type": { "tag": ":int" } }, { "tag": "field", "name": "c", "type": { "tag": ":char" } }, { "tag": "field", "name": "m", "type": { "tag": "enum", "name": "", "location": "example.h:32:5", "fields": [{ "tag": "field", "name": "X", "value": 0 }, { "tag": "field", "name": "Y", "value": 1 }, { "tag": "field", "name": "Z", "value": 2 }] } }] } }, { "tag": "field", "name": "blah", "type": { "tag": ":int" } }] },
{ "tag": "typedef", "name": "some_struct_t", "location": "example.h:38:3", "type": { "tag": ":struct", "name": "some_struct" } },
{ "tag": "union", "name": "my_union", "location": "example.h:40:7", "fields": [{ "tag": "field", "name": "c", "type": { "tag": ":char" } }, { "tag": "field", "name": "i", "type": { "tag": ":int" } }, { "tag": "field", "name": "d", "type": { "tag": ":double" } }] },
{ "tag": "enum", "name": "some_values", "location": "example.h:46:6", "fields": [{ "tag": "field", "name": "a_value", "value": 0 }, { "tag": "field", "name": "another_value", "value": 1 }, { "tag": "field", "name": "yet_another_value", "value": 2 }] },
{ "tag": "function", "name": "do_something", "location": "example.h:52:6", "parameters": [{ "tag": "parameter", "name": "p", "type": { "tag": ":pointer", "type": { "tag": "my_point_t" } } }, { "tag": "parameter", "name": "x", "type": { "tag": ":int" } }, { "tag": "parameter", "name": "y", "type": { "tag": ":int" } }], "return-type": { "tag": ":void" } }
]
