[
{ "tag": "const", "name": "CAIRO_HAS_SCRIPT_SURFACE", "location": "macros.h:88:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "CAIRO_HAS_TEE_SURFACE", "location": "macros.h:89:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "CAIRO_HAS_SVG_SURFACE", "location": "macros.h:90:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "CAIRO_HAS_XCB_SHM_FUNCTIONS", "location": "macros.h:91:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "CAIRO_HAS_USER_FONT", "location": "macros.h:92:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "CAIRO_HAS_XLIB_SURFACE", "location": "macros.h:93:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "CAIRO_HAS_XCB_SURFACE", "location": "macros.h:94:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "CAIRO_HAS_IMAGE_SURFACE", "location": "macros.h:95:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "CAIRO_HAS_GOBJECT_FUNCTIONS", "location": "macros.h:96:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "CAIRO_HAS_OBSERVER_SURFACE", "location": "macros.h:97:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "CAIRO_HAS_MIME_SURFACE", "location": "macros.h:98:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "CAIRO_HAS_PDF_SURFACE", "location": "macros.h:99:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "CAIRO_HAS_PNG_FUNCTIONS", "location": "macros.h:100:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "CAIRO_HAS_RECORDING_SURFACE", "location": "macros.h:101:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "CAIRO_HAS_PS_SURFACE", "location": "macros.h:102:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "CAIRO_HAS_FC_FONT", "location": "macros.h:103:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "CAIRO_HAS_GL_SURFACE", "location": "macros.h:104:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "CAIRO_HAS_FT_FONT", "location": "macros.h:105:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "CAIRO_HAS_GLX_FUNCTIONS", "location": "macros.h:106:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "CAIRO_HAS_XLIB_XRENDER_SURFACE", "location": "macros.h:107:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "CAIRO_HAS_EGL_FUNCTIONS", "location": "macros.h:108:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "CAIRO_VERSION_MICRO", "location": "macros.h:109:18", "type": { "tag": "__int128_t" }, "value": 10 },
{ "tag": "const", "name": "CAIRO_VERSION_MINOR", "location": "macros.h:110:18", "type": { "tag": "__int128_t" }, "value": 12 },
{ "tag": "const", "name": "CAIRO_VERSION_MAJOR", "location": "macros.h:111:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "CAIRO_MIME_TYPE_PNG", "location": "macros.h:112:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "image/png" },
{ "tag": "const", "name": "CAIRO_MIME_TYPE_JP2", "location": "macros.h:113:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "image/jp2" },
{ "tag": "const", "name": "CAIRO_MIME_TYPE_JPEG", "location": "macros.h:114:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "image/jpeg" },
{ "tag": "const", "name": "CAIRO_MIME_TYPE_UNIQUE_ID", "location": "macros.h:115:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "application/x-cairo.uuid" },
{ "tag": "const", "name": "CAIRO_MIME_TYPE_URI", "location": "macros.h:116:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "text/x-uri" }
]
